### ISSUE TITLE
Updating api for v6.0.0

### ISSUE THREAD

**Issue by ThomasOrtiz** [martinsileno/pubg-typescript-api#12]
PUBG API is updating their api to `v6.0.0`:

# Task List
- [x] Add `steam` and `kakao` to `PlatformRegion` enum.
- [x] Add [PC] participant.attributes.stats.rankPoints
- [x] Add [PC] match.attributes.seasonState
- [x] Add [PC] LogMatchDefinition.SeasonState
- [x] Add new [PC] `gameModeStats` attributes: [`bestRankPoints`, `dailyWins`, `rankPoints`, `swimDistance`, `weeklyWins`.
- [x] No need to remove deprecated `gameModeStats` since Xbox and old-pc seasons still use them.
- [x] If needed - Update `SeasonStats` api call to handle new and old api format
- [x] If needed - Update `matches` endpoint to handle new api format
- [x] Push my commits to GitHub
- [x] Open a pull request

# Major Updates
## New Ranking 
* For `XBOX` the original rating properties (as is) will still be available.
* For `PC` killPoints, winPoints, and their deltas will be deprecated for `RankPoint`.
* Deprecated killPoints, killPointsDelta, winPoints, and winPointsDelta will be "0" for PC beginning on 10/3.

## New `Player Season-Stats` and `Matches`:
**Matches:**
```
Old:  /shards/ {platform-region} /matches/{id}
New:  /shards/ {steam or kakao}  /matches/{id}
```
* Matches will support both formats so you can use either format to get matches from previous/new season

**Player's Season Stats:**
```
PC (after  10/3)   - /shards/    {steam or kakao}   /players/{playerId}/seasons/{seasonId}
PC (before 10/3)   - /shards/ {pc or xbox}-{region} /players/{playerId}/seasons/{seasonId}
Xbox               - /shards/ {pc or xbox}-{region} /players/{playerId}/seasons/{seasonId}
```
* New seasons will **have** to follow the new endpoint format
* _Does this means that we CANT use the new `rank` format for PC seasons before 10/3?_
  * Waiting on confirmation for this...

**Player by Id:**
```
Remains the same    - https://api.pubg.com/shards/{region}/players/{id}
```

# Source / Documentation
* [PUBG API Changelog 10/1/2018](https://mailchi.mp/01e4144eca8c/version-503-is-now-live-1444621?e=3db0d4bdae)
* [PUBG Api Changelog](https://documentation.pubg.com/en/changelog/changelog.html#v6-0-0-planned-for-10-03-18)

![image](https://user-images.githubusercontent.com/10877317/46294837-b04c6c00-c564-11e8-821b-233edc9bc600.png)

**Comment by martinsileno** [comment]
Hi,

thanks for the issue and the PR!

The only thing left to worry about is the removal of `killPoints`, `killPointsDelta`, `winPoints` and `winPointsDelta` from PC's participants attributes. 

I think the easiest way to handle it would be to mark those fields as nullable in `IParticipantAttributes` (and by consequence, mark the same fields as nullable in the class `Participant`). This way we would keep the same code working for both PC and XBOX, otherwise we'd have to split `Participant` objects according to the platform requested, and I don't really like that.

Something like this: https://gist.github.com/martinsileno/e84b6daa11f1469fd7ddb5dd6e913ea9.

If you have better ideas let me know!

Anyway, since they are marked as _deprecated_, according to their [release process](https://documentation.playbattlegrounds.com/en/versioning.html) they will still be available for two weeks after the release.

**Comment by ThomasOrtiz** [comment]
I like the idea of keeping one participant object instead of separating them out -- keeps the models more maintainable for now. 

I took your gist and updated my PR with your changes 👍

**Comment by ThomasOrtiz** [comment]
@martinsileno PUBG made another announcement today so I updated this issue to be generically for `v6.0.0` and updated notes.

**Comment by martinsileno** [comment]
PR merged and version [v1.5.0](https://github.com/martinsileno/pubg-typescript-api/releases/tag/v1.5.0) released! 🎉 

Only thing left is to add typing for `seasonState`, as soon as we know its format.
